import {Router} from 'express';import crypto from 'node:crypto';import {head,issueSignedToken,presignUrl} from '@vercel/blob';import auth from '../middleware/auth.js';import Screening from '../models/Screening.js';
const r=Router(),types=new Set(['image/jpeg','image/png']),max=12*1024*1024,privateAccess='private';
const pathFor=(user,id,name)=>`eyezen/users/${user}/screenings/${id}/${name}`;
const signedUrlLifetimeMs=15*60*1000;
export function validatePresignedGetUrl(value){const url=new URL(value);if(url.protocol!=='https:'||!url.hostname.endsWith('.private.blob.vercel-storage.com')||!url.searchParams.has('vercel-blob-delegation')||!url.searchParams.has('vercel-blob-signature'))throw Error('Private Blob GET signing did not produce a valid presigned URL.');return value}
function validatePresignedUrl(value,operation){const url=new URL(value);if(url.protocol!=='https:'||!url.searchParams.has('vercel-blob-delegation')||!url.searchParams.has('vercel-blob-signature'))throw Error('Blob signing did not produce a valid presigned URL.');return operation==='get'?validatePresignedGetUrl(value):value}
async function sign(pathname,operation,options={}){const validUntil=Date.now()+signedUrlLifetimeMs,token=await issueSignedToken({pathname,operations:[operation],validUntil}),signed=await presignUrl(token,{pathname,operation,access:privateAccess,validUntil,...options});return validatePresignedUrl(signed.presignedUrl,operation)}
export const createReadUrl=pathname=>sign(pathname,'get');
export const verifyInputBlob=async pathname=>{const result=await head(pathname);if(result.pathname!==pathname)throw Error('Private Blob returned a pathname different from the uploaded image reference.');return result.pathname};
r.use(auth);
r.post('/upload-intent',async(req,res)=>{try{const {contentType,size,extension}=req.body||{};if(!types.has(contentType)||!Number.isInteger(size)||size<1||size>max||!['jpg','jpeg','png'].includes(String(extension).toLowerCase()))return res.status(400).json({message:'Unsupported image upload'});const id=crypto.randomUUID(),path=pathFor(req.user.id,id,`input.${extension==='jpeg'?'jpg':extension}`);res.json({uploadId:id,inputBlobPath:path,uploadUrl:await sign(path,'put',{allowedContentTypes:[contentType],maximumSizeInBytes:max})})}catch(error){console.error('Blob upload intent failed:',error.message);res.status(503).json({message:'Private upload storage unavailable'})}});
r.get('/screenings/:id/:asset',async(req,res)=>{const fields={input:'inputBlobPath',lesion:'lesionBlobPath',gradcam:'gradcamBlobPath',report:'reportBlobPath'},field=fields[req.params.asset];if(!field)return res.status(404).json({message:'Asset not found'});const screening=await Screening.findOne({_id:req.params.id,createdBy:req.user.id});if(!screening?.[field])return res.status(404).json({message:'Asset not found'});try{res.json({url:await sign(screening[field],'get')})}catch(error){console.error('Blob read signing failed:',error.message);res.status(503).json({message:'Private asset unavailable'})}});
export const createAssetUploads=async(user,id)=>{const paths={lesionBlobPath:pathFor(user,id,'lesion.png'),gradcamBlobPath:pathFor(user,id,'gradcam.png'),reportBlobPath:pathFor(user,id,'report.pdf')};const uploads={lesionUploadUrl:await sign(paths.lesionBlobPath,'put',{allowedContentTypes:['image/png']}),gradcamUploadUrl:await sign(paths.gradcamBlobPath,'put',{allowedContentTypes:['image/png']}),reportUploadUrl:await sign(paths.reportBlobPath,'put',{allowedContentTypes:['application/pdf']})};return{paths,uploads}};
export default r;
