import {Router} from 'express';import crypto from 'node:crypto';import {issueSignedToken,presignUrl} from '@vercel/blob';import auth from '../middleware/auth.js';import Screening from '../models/Screening.js';
const r=Router(),types=new Set(['image/jpeg','image/png']),max=12*1024*1024,privateAccess='private';
const pathFor=(user,id,name)=>`eyezen/users/${user}/screenings/${id}/${name}`;
async function sign(pathname,operation,options={}){const token=await issueSignedToken({operations:[operation]});const signed=await presignUrl(token,{pathname,operation,access:privateAccess,validFor:'15m',...options});return signed.presignedUrl}
export const createReadUrl=pathname=>sign(pathname,'get');
r.use(auth);
r.post('/upload-intent',async(req,res)=>{try{const {contentType,size,extension}=req.body||{};if(!types.has(contentType)||!Number.isInteger(size)||size<1||size>max||!['jpg','jpeg','png'].includes(String(extension).toLowerCase()))return res.status(400).json({message:'Unsupported image upload'});const id=crypto.randomUUID(),path=pathFor(req.user.id,id,`input.${extension==='jpeg'?'jpg':extension}`);res.json({uploadId:id,inputBlobPath:path,uploadUrl:await sign(path,'put',{allowedContentType:contentType,maximumSizeInBytes:max})})}catch(error){console.error('Blob upload intent failed:',error.message);res.status(503).json({message:'Private upload storage unavailable'})}});
r.get('/screenings/:id/:asset',async(req,res)=>{const fields={input:'inputBlobPath',lesion:'lesionBlobPath',gradcam:'gradcamBlobPath',report:'reportBlobPath'},field=fields[req.params.asset];if(!field)return res.status(404).json({message:'Asset not found'});const screening=await Screening.findOne({_id:req.params.id,createdBy:req.user.id});if(!screening?.[field])return res.status(404).json({message:'Asset not found'});try{res.json({url:await sign(screening[field],'get')})}catch(error){console.error('Blob read signing failed:',error.message);res.status(503).json({message:'Private asset unavailable'})}});
export const createAssetUploads=async(user,id)=>{const paths={lesionBlobPath:pathFor(user,id,'lesion.png'),gradcamBlobPath:pathFor(user,id,'gradcam.png'),reportBlobPath:pathFor(user,id,'report.pdf')};const uploads={lesionUploadUrl:await sign(paths.lesionBlobPath,'put',{allowedContentType:'image/png'}),gradcamUploadUrl:await sign(paths.gradcamBlobPath,'put',{allowedContentType:'image/png'}),reportUploadUrl:await sign(paths.reportBlobPath,'put',{allowedContentType:'application/pdf'})};return{paths,uploads}};
export default r;
