import {Router} from 'express';import crypto from 'node:crypto';import {head,issueSignedToken,presignUrl} from '@vercel/blob';import {generateClientTokenFromReadWriteToken} from '@vercel/blob/client';import auth from '../middleware/auth.js';import Screening from '../models/Screening.js';
const r=Router(),types=new Set(['image/jpeg','image/png']),max=12*1024*1024,privateAccess='private';
const pathFor=(user,id,name)=>`eyezen/users/${user}/screenings/${id}/${name}`;
const signedUrlLifetimeMs=15*60*1000;
export function validatePresignedGetUrl(value){const url=new URL(value);if(url.protocol!=='https:'||!url.hostname.endsWith('.private.blob.vercel-storage.com')||!url.searchParams.has('vercel-blob-delegation')||!url.searchParams.has('vercel-blob-signature'))throw Error('Private Blob GET signing did not produce a valid presigned URL.');return value}
function validatePresignedUrl(value,operation){const url=new URL(value);if(url.protocol!=='https:'||!url.searchParams.has('vercel-blob-delegation')||!url.searchParams.has('vercel-blob-signature'))throw Error('Blob signing did not produce a valid presigned URL.');return operation==='get'?validatePresignedGetUrl(value):value}
async function sign(pathname,operation,options={}){const validUntil=Date.now()+signedUrlLifetimeMs,token=await issueSignedToken({pathname,operations:[operation],validUntil}),signed=await presignUrl(token,{pathname,operation,access:privateAccess,validUntil,...options});return validatePresignedUrl(signed.presignedUrl,operation)}
export const createReadUrl=pathname=>sign(pathname,'get');
export const verifyBlob=async pathname=>{const result=await head(pathname);if(result.pathname!==pathname)throw Error('Private Blob returned a pathname different from the expected storage reference.');return result.pathname};
export const verifyInputBlob=verifyBlob;
r.use(auth);
r.post('/upload-intent',async(req,res)=>{try{const {contentType,size,extension}=req.body||{};if(!types.has(contentType)||!Number.isInteger(size)||size<1||size>max||!['jpg','jpeg','png'].includes(String(extension).toLowerCase()))return res.status(400).json({message:'Unsupported image upload'});const id=crypto.randomUUID(),path=pathFor(req.user.id,id,`input.${extension==='jpeg'?'jpg':extension}`),uploadToken=await generateClientTokenFromReadWriteToken({pathname:path,allowedContentTypes:[contentType],maximumSizeInBytes:max,validUntil:Date.now()+signedUrlLifetimeMs,addRandomSuffix:false});res.json({uploadId:id,inputBlobPath:path,uploadToken})}catch(error){console.error('Blob upload intent failed:',error.message);res.status(503).json({message:'Private upload storage unavailable'})}});
r.get('/screenings/:id/:asset',async(req,res)=>{const fields={input:'inputBlobPath',lesion:'lesionBlobPath',gradcam:'gradcamBlobPath',report:'reportBlobPath'},field=fields[req.params.asset];if(!field)return res.status(404).json({message:'Asset not found'});const screening=await Screening.findOne({_id:req.params.id,createdBy:req.user.id});if(!screening?.[field])return res.status(404).json({message:'Asset not found'});try{await verifyBlob(screening[field]);res.json({url:await sign(screening[field],'get')})}catch(error){if(error?.name==='BlobNotFoundError')return res.status(404).json({message:'Asset is no longer available'});console.error('Blob read signing failed:',error.message);res.status(503).json({message:'Private asset unavailable'})}});
export const normalizeUrlPathname=value=>decodeURIComponent(value).replace(/^\/+/, '');
const createWriteUrl=async(asset,pathname,contentType)=>{const url=await sign(pathname,'put',{allowedContentTypes:[contentType]}),expected=normalizeUrlPathname(pathname),urlPath=normalizeUrlPathname(new URL(url).pathname),matches=urlPath===expected;console.info('Signed PUT pathname check:',`asset=${asset}`,`expected=${expected}`,`urlPath=${urlPath}`,`match=${matches}`);if(!matches)console.error('Blob signed URL validation failed:',`asset=${asset}`);return url};
export const createAssetUploads=async paths=>{const uploads={lesionUploadUrl:await createWriteUrl('lesion',paths.lesionBlobPath,'image/png'),gradcamUploadUrl:await createWriteUrl('gradcam',paths.gradcamBlobPath,'image/png'),reportUploadUrl:await createWriteUrl('report',paths.reportBlobPath,'application/pdf')};return{paths,uploads}};
export default r;
