import {Router} from 'express';import multer from 'multer';import axios from 'axios';import fs from 'fs';import crypto from 'node:crypto';import auth from '../middleware/auth.js';import Screening from '../models/Screening.js';import {createAssetUploads,createReadUrl} from './blob.js';
const allowedExtensions=new Set(['.jpg','.jpeg','.png']),allowedMimes=new Set(['image/jpeg','image/jpg','image/png','image/x-png']),blobMode=()=>process.env.STORAGE_MODE==='vercel-blob';
function getMlServiceUrl(){if(process.env.ML_SERVICE_URL)return process.env.ML_SERVICE_URL.replace(/\/$/,'');if(process.env.VERCEL_URL)return `https://${process.env.VERCEL_URL}/api/ml`;return 'http://127.0.0.1:8000'}
process.env.ML_SERVICE_URL=getMlServiceUrl();
const r=Router(),upload=multer({dest:'uploads/',limits:{fileSize:12*1024*1024},fileFilter:(_,f,cb)=>{const ext=f.originalname.slice(f.originalname.lastIndexOf('.')).toLowerCase();cb(null,allowedMimes.has((f.mimetype||'').toLowerCase())||allowedExtensions.has(ext))}});r.use(auth);
const withAssetUrls=async item=>{const record=item.toObject?item.toObject():item;if(!record.lesionBlobPath&&!record.gradcamBlobPath&&!record.reportBlobPath)return record;const result={...(record.result||{})};for(const[field,key]of[['lesionBlobPath','lesionOverlayUrl'],['gradcamBlobPath','gradcamUrl'],['reportBlobPath','reportUrl']])if(record[field])try{result[key]=await createReadUrl(record[field])}catch{result[key]=null}return{...record,result}};
r.get('/',async(req,res)=>res.json(await Promise.all((await Screening.find({createdBy:req.user.id}).sort('-createdAt')).map(withAssetUrls))));r.get('/dashboard',async(req,res)=>{const owned=await Screening.find({createdBy:req.user.id}).sort('-createdAt'),records=await Promise.all(owned.map(withAssetUrls));res.json({total:records.length,refer:owned.filter(x=>(x.result.decision||x.result.referralDecision)==='REFER').length,records})});r.get('/:id',async(req,res)=>{const item=await Screening.findOne({_id:req.params.id,createdBy:req.user.id});if(!item)return res.status(404).json({message:'Screening not found'});res.json(await withAssetUrls(item))});
r.post('/',upload.single('image'),async(req,res)=>{let localPath;try{const patient={name:req.body.patientName||'',recordId:req.body.recordId||'',age:req.body.age||undefined},form=new FormData(),isBlob=blobMode();if(isBlob){const inputBlobPath=String(req.body.inputBlobPath||'');if(!inputBlobPath.startsWith(`eyezen/users/${req.user.id}/screenings/`))return res.status(400).json({message:'Invalid uploaded image reference'});const screeningId=crypto.randomUUID(),assets=await createAssetUploads(req.user.id,screeningId);form.append('imageUrl',await createReadUrl(inputBlobPath));form.append('assetUploads',JSON.stringify(assets.uploads));form.append('assetPaths',JSON.stringify(assets.paths));form.append('storageMode','vercel-blob');form.append('patientName',patient.name);form.append('recordId',patient.recordId);form.append('age',String(patient.age??''));const ml=await axios.post(`${process.env.ML_SERVICE_URL}/infer`,form);const result=ml.data;const item=await Screening.create({createdBy:req.user.id,patient,inputBlobPath,...assets.paths,result:{...result,lesionOverlayUrl:null,gradcamUrl:null,reportUrl:null}});return res.status(201).json(await withAssetUrls(item))}if(!req.file)return res.status(400).json({message:'Unsupported file type. Upload a JPG or PNG fundus image.'});localPath=req.file.path;form.append('image',new Blob([fs.readFileSync(localPath)],{type:req.file.mimetype||'application/octet-stream'}),req.file.originalname);form.append('patientName',patient.name);form.append('recordId',patient.recordId);form.append('age',String(patient.age??''));const ml=await axios.post(`${process.env.ML_SERVICE_URL}/infer`,form);const result=Object.fromEntries(Object.entries(ml.data).map(([k,v])=>[k,typeof v==='string'&&v.startsWith('/')?`${process.env.ML_SERVICE_URL}${v}`:v]));const item=await Screening.create({createdBy:req.user.id,patient,imageUrl:`${req.protocol}://${req.get('host')}/uploads/${req.file.filename}`,result});res.status(201).json(item)}catch(error){console.error('Screening inference failed:',error.message);res.status(502).json({message:error.response?.data?.detail||'Inference service unavailable'})}finally{if(localPath)fs.unlink(localPath,()=>{})}});
export default r;
